- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     
   
  tasks:
    - name: Generate Access Token From FortiCloud Auth Server.
      uri:
        url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
        method: POST
        body_format: json
        return_content: true
        headers:
          Content-Type: application/json
        body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
      register: tokeninfo
#
## add model device
#
    - name: Add model device {{adom}}/{{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        #bypass_validation: True
        params:
          - url: '/dvm/cmd/add/device'
            data:
              adom: '{{adom}}'
              flags: [ create_task , nonblocking ]
              device:
                  desc:
                  mgmt_mode: 'fmg'
                  model_device: 1
                  flags: [ is_model, linked_to_model ]
                  add_model: 1
                  name: '{{fgt_name}}'
                  sn: "{{fgt_sn}}"
                  os_type: 'fos'
                  os_ver: '6.0'
                  mr: 4
                  patch: 7
                 
      register: fmgtask

    - name: Wait for add device task
      fmgr_fact:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        facts:
            selector: 'task_task'
            params:
                task: '{{fmgtask.meta.response_data.taskid}}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error' and 'devsnexist' not in taskinfo.meta.response_data.line[0].detail

     
    - name: Set auto-link mode on model device
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: update
        params:
          - url: '/dvmdb/adom/{{adom}}/device/{{fgt_name}}'
            data:
              flags: [ is_model, linked_to_model ]
              
#---------------------------------------------------------------------------------------   
