- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     FORTICLOUD_APIID: 7F217031-9D17-48DB-9D2F-5B45E4761F01
     FORTICLOUD_PASSWD: 402bef868a9f3270445974d9c9624c4d!1Aa
  
  tasks:
   - name: Generate Access Token From FortiCloud Auth Server.
     uri:
       url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
       method: POST
       body_format: json
       return_content: true
       headers:
         Content-Type: application/json
       body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
     register: tokeninfo
   - name: del deice {{fgt}}
    fmgr_generic:
       method: execv
       forticloud_access_token: '{{ tokeninfo.json.access_token }}'
       params:
         - url: '/dvm/cmd/del/device'
           data:
             adom: root
             device: '{{fgt}}'
       ignore_errors: yes
