- hosts: fortimanagers
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Show facts
     debug:
       var: ansible_facts
   - name: Interface configuration.
     fmgr_dvmdb_device:
        bypass_validation: False
        admom: root
        device: BP_Branch1
        
