- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     FORTICLOUD_APIID: 7F217031-9D17-48DB-9D2F-5B45E4761F01
     FORTICLOUD_PASSWD: 402bef868a9f3270445974d9c9624c4d!1Aa
   
  tasks:
   - name: Generate Access Token From FortiCloud Auth Server.
     uri:
       url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
       method: POST
       body_format: json
       return_content: true
       headers:
         Content-Type: application/json
       body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
     register: tokeninfo

### IPsec template
#    - name: delete IPsec template
#      fmgr_generic:
#        method: delete
#        params:
#          - url: '/pm/template/adom/{{adom}}/{{ipsec_tpt}}'
#      ignore_errors: yes

    - name: make IPsec template
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: set
        params:
          - url: '/pm/template/adom/{{adom}}'
            data:
              - name: '{{ipsec_tpt}}'
                type: pkg
                'scope member': []
                'template setting':
                  stype: ipsec
                  widgets: [ ipsec ]

    - name: configure IPsec template tunnel
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: set
        params:
          - url: '/pm/config/adom/{{adom}}/template/{{ipsec_tpt}}/device/template/widget/ipsec/action-list'
            data:
              - action: 'conf-ipsec-template'
                model: all
                # WARNing: do NOT use ansible variables here, fex {{ipsec_tun}}
                #   created tunnel will be invalid
                # extra WARNing: 'value:' has to be one json term packed in one string
                #   do not unfold components in yaml
                # extra WARNing: this string is verry sensitive and like, ee!moe!shunul!!
                #   make and log the request in gui, then paste it here literally
                #   orelse log from the cli: dia deb ena; dia deb service cdb 255;

                value: "{\"local-addr-type\":\"metadata\",\"automatic-routing\":\"enable\",\"add-route\":\"enable\",\"assign-ip\":\"enable\",\"authmethod\":\"psk\",\"auto-discovery-forwarder\":\"disable\",\"auto-discovery-receiver\":\"disable\",\"auto-discovery-sender\":\"disable\",\"dpd\":\"on-idle\",\"dpd-retrycount\":3,\"dpd-retryinterval\":\"20\",\"idle-timeout\":\"disable\",\"idle-timeoutinterval\":15,\"ike-version\":\"2\",\"interface\":\"wan1\",\"ipv4-end-ip\":\"0.0.0.0\",\"ipv4-netmask\":\"255.255.255.255\",\"ipv4-start-ip\":\"0.0.0.0\",\"keylife\":86400,\"mode-cfg\":\"disable\",\"name\":\"ipsec_tun\",\"net-device\":\"disable\",\"network-id\":0,\"network-overlay\":\"disable\",\"psksecret\":\"fortinet\",\"remote-gw\":\"192.168.1.11\",\"tunnel-search\":\"selectors\",\"type\":\"static\",\"remote-subnet\":[\"0.0.0.0\",\"255.255.255.255\"],\"local-intf\":\"wan1\",\"local-addr-meta\":\"0.0.0.0\",\"system interface\":{\"remote-ip\":\"\",\"ip\":\"\"}}"

                'var-list':
                  - name: "vpn ipsec phase1-interface/tunnel-search"
                    override: 0
                  - name: "vpn ipsec phase1-interface/ipv4-netmask"
                    override: 0
                  - name: "vpn ipsec phase1-interface/ipv4-end-ip"
                    override: 0
                  - name: "vpn ipsec phase1-interface/ipv4-start-ip"
                    override: 0
                  - name: "vpn ipsec phase1-interface/ike-version"
                    override: 0
                  - name: "vpn ipsec phase1-interface/assign-ip"
                    override: 0
                  - name: "vpn ipsec phase1-interface/network-overlay"
                    override: 0
                  - name: "vpn ipsec phase1-interface/network-id"
                    override: 0
                  - name: "vpn ipsec phase1-interface/mode-cfg"
                    override: 0
                  - name: "vpn ipsec phase1-interface/dpd"
                    override: 0
                  - name: "vpn ipsec phase1-interface/keylife"
                    override: 0
                  - name: "vpn ipsec phase1-interface/dpd-retryinterval"
                    override: 0
                  - name: "vpn ipsec phase1-interface/dpd-retrycount"
                    override: 0
                  - name: "vpn ipsec phase1-interface/idle-timeoutinterval"
                    override: 0
                  - name: "vpn ipsec phase1-interface/idle-timeout"
                    override: 0
                  - name: "vpn ipsec phase1-interface/auto-discovery-forwarder"
                    override: 0
                  - name: "vpn ipsec phase1-interface/auto-discovery-receiver"
                    override: 0
                  - name: "vpn ipsec phase1-interface/auto-discovery-sender"
                    override: 0
                  - name: "vpn ipsec phase1-interface/add-route"
                    override: 0
                  - name: "vpn ipsec phase1-interface/net-device"
                    override: 0
                  - name: "vpn ipsec phase1-interface/certificate"
                    override: 0
                  - name: "vpn ipsec phase1-interface/authmethod"
                    override: 0
                  - name: "vpn ipsec phase1-interface/psksecret"
                    override: 0
                  - name: "vpn ipsec phase1-interface/remotegw-ddns"
                    override: 0
                  - name: "vpn ipsec phase1-interface/remote-gw"
                    override: 0
                  - name: "vpn ipsec phase1-interface/type"
                    override: 0
                  - name: "vpn ipsec phase1-interface/interface"
                    override: 0
                  - name: "vpn ipsec phase1-interface/name"
                    override: 0

### IPsec
    - name: assign IPsec template to device {{fgt}}
      fmgr_generic:
      forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: set
        params:
          - url: '/pm/template/adom/{{adom}}'
            data:
              name: '{{ipsec_tpt}}'
              type: pkg
              'scope member':
                - name: '{{fgt}}'
                  vdom: root
              'template setting':
                stype: ipsec
                widgets: [ ipsec ]

### Install template to model device 1st, then configure adom dyn intf and policies, then install PP

    - name: Install template to model dev {{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        params:
          - url: '/securityconsole/install/device'
            data:
              adom: '{{adom}}'
              dev_rev_comments:  'v1: {{ipsec_tpt}} to {{fgt}}'
              #flags: [ none ]
              scope:
                - name: '{{fgt}}'
                  vdom: root
      register: fmgtask

    - name: Wait for device install to task
      fmgr_fact:
        facts:
            selector: 'task_task'
            params:
                task: '{{fmgtask.meta.response_data.task}}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error'

### do adom now, dyn_intf, policies -----------------------------------------------
    - name: Create script {{ipsec_adom_script}} to configure adom {{adom}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: set
        params:
          - url: '/dvmdb/adom/{{adom}}/script'
            data:
              - name: '{{ipsec_adom_script}}'
                target: adom_database
                type: cli
                content: |
                  config dynamic interface
                      edit "{{ipsec_tun}}"
                          config dynamic_mapping
                              edit "{{fgt}}"-"root"
                                  set local-intf {{ipsec_tun}}
                              next
                          end
                          #set default-mapping enable
                          #set defmap-intf "{{ipsec_tun}}"
                      next
                  end
                  #2:# config platform mapping ? who/when does this
                  config firewall policy
                      edit 0
                          set name "{{ipsec_tun}} out"
                          set srcintf "{{ipsec_tun}}"
                          set dstintf "any"
                          set srcaddr "all"
                          set dstaddr "all"
                          set action accept
                          set schedule "always"
                          set service "ALL"
                          set nat enable
                      next
                      edit 0
                          set name "{{ipsec_tun}} in"
                          set srcintf "any"
                          set dstintf "{{ipsec_tun}}"
                          set srcaddr "all"
                          set dstaddr "all"
                          set action accept
                          set schedule "always"
                          set service "ALL"
                          set nat enable
                      next
                  end

    - name: run script {{ipsec_adom_script}} on adom {{adom}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        params:
          - url: '/dvmdb/adom/{{adom}}/script/execute'
            data:
              adom: '{{adom}}'
              package: '{{polpkg}}'
              script: '{{ipsec_adom_script}}'

      register: fmgtask

    - name: wait for run script on adom task
      fmgr_fact:
        facts:
            selector: 'task_task'
            params:
                task: '{{fmgtask.meta.response_data.task}}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error'

#### re-install polpkg to model dev with the new ipsec policies

    - name: Install polpkg {{polpkg}} to model dev {{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        params:
          - url: '/securityconsole/install/package'
            data:
              adom: '{{adom}}'
              adom_rev_comments: 'v2: ipsec policies {{adom}}/{{polpkg}} copy to model {{fgt}}'
              dev_rev_comments:  'v2: ipsec policies {{adom}}/{{polpkg}} copy only'
              flags: [ copy_only ]
              pkg: '{{polpkg}}'
              scope:
                - name: '{{fgt}}'
                  vdom: root
      register: fmgtask

    - name: Wait for install polpkg to model dev task
      fmgr_fact:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        facts:
            selector: 'task_task'
            params:
                task: '{{fmgtask.meta.response_data.task}}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error'
