- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     
     fsw_nm: FortiSwitch
     fsw_tpt: FSW_template
     fap_prof: AP-P
     fsw: FSW108E
     sdwan: SDWan
     sdwan_tpt: SDWAN_template
     ipsec_tpt: IPsec_template
     ipsec_tun: ipsec_tun
     script_adom: prep_adom
     polpkg: ztp_pp
     adom: ztp_demo
     
  tasks:
   - name: Generate Access Token From FortiCloud Auth Server.
     uri:
       url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
       method: POST
       body_format: json
       return_content: true
       headers:
         Content-Type: application/json
       body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
     register: tokeninfo
   
