- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     FORTICLOUD_APIID: 7F217031-9D17-48DB-9D2F-5B45E4761F01
     FORTICLOUD_PASSWD: 402bef868a9f3270445974d9c9624c4d!1Aa
     
     fsw_nm: FortiSwitch
     fsw_tpt: FSW_template
     fap_prof: AP-P
     fsw: FSW108E
     sdwan: SDWan
     sdwan_tpt: SDWAN_template
     ipsec_tpt: IPsec_template
     ipsec_tun: ipsec_tun
     script_adom: prep_adom
     polpkg: BP_PP
     

   
  tasks:
   - name: Generate Access Token From FortiCloud Auth Server.
     uri:
       url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
       method: POST
       body_format: json
       return_content: true
       headers:
         Content-Type: application/json
       body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
     register: tokeninfo
   - name: add adom {{adom}}
      fmgr_generic:
        method: add
        params:
          - url: '/dvmdb/adom'
            data:
              - name: '{{adom}}'
                flags: [ central_sdwan, no_vpn_console ] # no_vpn_console, 
                os_ver: '6.0'
                mr: 4  
    
