- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     

     script_adom: prep_adom
     script_dynmap: config_dynmap
     script_dev: Full_Config_Model_dev
     ipsec_adom_script: ipsec_adom_script
     
   
  tasks:
    - name: Generate Access Token From FortiCloud Auth Server.
      uri:
        url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
        method: POST
        body_format: json
        return_content: true
        headers:
          Content-Type: application/json
        body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
      register: tokeninfo

## add model device
    
    - name: Add model device
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        #bypass_validation: True
        params:
          - url: '/dvm/cmd/add/device'
            data:
              adom: '{{adom}}'
              flags: [ create_task , nonblocking ]
              device:
                  adm_usr:  admin
                  adm_pass: '{{fgt_pw}}'
                  desc:
                  mgmt_mode: 'fmg'
                  model_device: 1
                  meta fields:
                    LOOPBACK0: '{{loopback0}}'
                    HOSTNAME: '{{fgt}}'
                    NET_A: '{{net_a}}'
                    NET_B: '{{net_b}}'
                    VPN_LTE_GH_IP: '{{vpn_lte_gh_ip}}'
                    VPN_LTE_FRA_IP: '{{vpn_lte_fra_ip}}'
                    VPN_DSL_GH_IP: '{{vpn_dsl_gh_ip}}'
                    VPN_DSL_FRA_IP: '{{vpn_dsl_fra_ip}}'
                    VPN_PSK: '{{vpn_psk}}'
                    VPN_LTE_USER: '{{vpn_lte_user}}'
                    VPN_LTE_PASSWORD: '{{vpn_lte_password}}'
                    VPN_DSL_USER: '{{vpn_dsl_user}}'
                    VPN_DSL_PASSWORD: '{{vpn_dsl_password}}'
                  flags: [ is_model, linked_to_model ]
                  add_model: 1
                  name: '{{fgt}}'
                  sn: "{{fgt_sn}}"
                  os_type: 'fos'
                  os_ver: '6.0'
                  mr: 4
                  patch: 7
                  
      register: fmgtask
#------------------------------------------------------------------      
    - name: Wait for add device task
      fmgr_fact:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        facts:
            selector: 'task_task'
            params:
                task: '{{fmgtask.meta.response_data.taskid}}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error' and 'devsnexist' not in taskinfo.meta.response_data.line[0].detail
        
#------------------------------------------------------------------   
    - name: Set auto-link mode on model device
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: update
        params:
          - url: '/dvmdb/adom/{{adom}}/device/{{fgt}}'
            data:
              flags: [ is_model, linked_to_model ]
              
#------------------------------------------------------------------
    - name: Set {{adom}}/{{polpkg}} install target => {{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: set
        params:
          - url: '/pm/pkg/adom/{{adom}}/{{polpkg}}'
            data:
              'scope member':
                - name: '{{fgt}}'
                  vdom: root
 
#------------------------------------------------------------------
#    - name: Run script {{script_dev}} on model dev {{fgt}}
#      fmgr_generic:
#        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
#        method: exec
#        params:
#          - url: '/dvmdb/adom/{{adom}}/script/execute'
#            data:
#              adom: '{{adom}}'
#              scope:
#                - name: '{{fgt}}'
#                  vdom: global
#              script: '{{script_dev}}'

#      register: fmgtask
#    - name: Wait for run script on model device task
#      fmgr_fact:
#        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
#        facts:
#            selector: 'task_task'
#            params:
#                task: '{{fmgtask.meta.response_data.task}}'
#      register: taskinfo
#      until: taskinfo.meta.response_data.percent == 100
#      retries: 30
#      delay: 5
#      failed_when: taskinfo.meta.response_data.state == 'error'
      
      #------------------------------------------------------------------
      
      ### FSW -------------------------------------------------------
 
 #   - name: Create model FSW
 #     fmgr_generic:
 #       forticloud_access_token: '{{ tokeninfo.json.access_token }}'
 #       method: set # update add
 #       params:
 #         - url: '/pm/config/device/{{fgt}}/vdom/root/switch-controller/managed-switch'
 #           push: 1             # auto-copy to (model) fgt
 #           data:
 #             name: '{{fsw_nm}}'
 #             switch-id: '{{fsw_sn}}'
 #             fsw-wan1-peer: 'internal'
#
#          - url: '/pm/config/adom/{{adom}}/obj/fsp/managed-switch/{{fsw_sn}}'
#            data:
#              name: '{{fsw_nm}}'
#              template: '{{fsw_tpt}}'

#    - name: Assign device and template to model FSW
#      fmgr_generic:
#        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
#        method: update
#        params:
#          - url: "/pm/config/adom/{{adom}}/obj/fsp/managed-switch/{{fsw_sn}}"
#            'scope member':
#              - name: '{{fgt}}'
#                vdom: root
#            data: # 
#              name: '{{fsw_nm}}'
              #template: '{{fsw_tpt}}'
              #1prefer-img-ver: "6.4.5-b00461"

