- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     

     script_adom: prep_adom
     script_dynmap: config_dynmap
     script_dev: config_modeldevs
     ipsec_adom_script: ipsec_adom_script
     
   
  tasks:
    - name: Generate Access Token From FortiCloud Auth Server.
      uri:
        url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
        method: POST
        body_format: json
        return_content: true
        headers:
          Content-Type: application/json
        body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
      register: tokeninfo
#
## add model device
#
    - name: Add model device {{adom}}/{{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        #bypass_validation: True
        params:
          - url: '/dvm/cmd/add/device'
            data:
              adom: '{{adom}}'
              flags: [ create_task , nonblocking ]
              device:
                  adm_usr:  admin
                  adm_pass: '{{fgt_pw}}'
                  desc:
                  mgmt_mode: 'fmg'
                  model_device: 1
                  meta fields:
                    BRANCH_ID: '{{brnach_id}}'
                    MGT_IP: '{{mgt_ip}}'
                    STAFF_SUBNET: '{{staff_subnet}}'
                    IOT_SUBNET: '{{iot_subnet}}'
                    GUEST_SUBNET: '{{guest_subnet}}'
                    USER_SUBNET: '{{user_subnet}}'
                    POS_SUBNET: '{{pos_subnet}}'
                    
                    Company/Organization: '{{company}}'
                  flags: [ is_model, linked_to_model ]
                  add_model: 1
                  name: '{{fgt}}'
                  sn: "{{fgt_sn}}"
                  os_type: 'fos'
                  os_ver: '7.0'
                  mr: 0
                  patch: 1
                  
      register: fmgtask
#------------------------------------------------------------------      
    - name: Wait for add device task
      fmgr_fact:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        facts:
            selector: 'task_task'
            params:
                task: '{{fmgtask.meta.response_data.taskid}}'
      register: taskinfo
      until: taskinfo.meta.response_data.percent == 100
      retries: 30
      delay: 5
      failed_when: taskinfo.meta.response_data.state == 'error' and 'devsnexist' not in taskinfo.meta.response_data.line[0].detail
        
#------------------------------------------------------------------   
    - name: Set auto-link mode on model device
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: update
        params:
          - url: '/dvmdb/adom/{{adom}}/device/{{fgt}}'
            data:
              flags: [ is_model, linked_to_model ]
              
#------------------------------------------------------------------
    - name: Set {{adom}}/{{polpkg}} install target => {{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: set
        params:
          - url: '/pm/pkg/adom/{{adom}}/{{polpkg}}'
            data:
              'scope member':
                - name: '{{fgt}}'
                  vdom: root
#------------------------------------------------------------------
    - name: Set system teplate
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: set
        params:
          - url: '/pm/devprof/adom/{{adom}}/{{sys_tpt}}'
            data:
              'scope member':
                - name: '{{fgt}}'
                  vdom: root
#------------------------------------------------------------------
    - name: Run script {{script_dev}} on model dev {{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        params:
          - url: '/dvmdb/adom/{{adom}}/script/execute'
            data:
              adom: '{{adom}}'
              scope:
                - name: '{{fgt}}'
                  vdom: global
              script: '{{script_dev}}'

      register: fmgtask

