- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
     
     fsw_nm: FSW108E
     fsw_tpt: FSW108E
     fap_prof: AP-P
     sdwan: SDWan
     sdwan_tpt: SDWAN_template
     ipsec_tpt: IPsec_template
     ipsec_tun: ipsec_tun
     script_adom: prep_adom
     script_dynmap: config_dynmap
     script_dev: config_modeldevs
     polpkg: BP_PP
     ipsec_adom_script: ipsec_adom_script
     
   
  tasks:
    - name: Generate Access Token From FortiCloud Auth Server.
      uri:
        url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
        method: POST
        body_format: json
        return_content: true
        headers:
          Content-Type: application/json
        body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
      register: tokeninfo
#
## add model device
#
    - name: Add model device {{adom}}/{{fgt}}
      fmgr_generic:
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        method: exec
        #bypass_validation: True
        params:
          - url: '/dvm/cmd/add/device'
            data:
              adom: '{{adom}}'
              flags: [ create_task , nonblocking ]
              device:
                  adm_usr:  admin
                  adm_pass: '{{fgt_pw}}'
                  desc:
                  mgmt_mode: 'fmg'
                  model_device: 1
                  meta fields:
                    POC_POS: '{{pos_subnet}}'
                  flags: [ is_model, linked_to_model ]
                  add_model: 1
                  name: '{{fgt}}'
                  sn: "{{fgt_sn}}"
                  os_type: 'fos'
                  os_ver: '6.0'
                  mr: 4
                  patch: 6
                  # prefer_img_ver: "6.4.6-b1879"
      register: fmgtask
