- hosts: all
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
   
  tasks:
   - name: Generate Access Token From FortiCloud Auth Server.
     uri:
       url: https://customerapiauth.fortinet.com/api/v1/oauth/token/
       method: POST
       body_format: json
       return_content: true
       headers:
         Content-Type: application/json
       body: '{"username": "{{ FORTICLOUD_APIID }}", "password": "{{ FORTICLOUD_PASSWD }}", "client_id": "FortiManager", "grant_type": "password"}'
     register: tokeninfo
     
   - name: Configure IPv4 addresses.
     fmgr_firewall_address:
        adom: root
        state: present
        enable_log: true
        forticloud_access_token: '{{ tokeninfo.json.access_token }}'
        firewall_address:
          name: Win11
          comment: from Ansible
          organization: Fortinet
          start-ip: 192.168.1.5
          end-ip: 192.168.1.11
          type: iprange
          associated-interface: any
